title = "clio-greeter"
description = ""
version = "0.1.0"
license = "ISC"
main = "index.clio"
keywords = ""

[author]
name = "Garrit Franke"
website = "garrit.xyz"

[scripts]
test = "No tests specified"

[dependencies]
stdlib = "latest"
